### ISSUE TITLE
Enabling tooltips in Advanced mode

### ISSUE THREAD

**Issue by digital-carver** [Gitoffthelawn/uBlock-Deluxe#6]
Hi! This may or may not be something you'd like to add to the style, but I figure you're most likely to know how to do this:  
I'd like to have tooltips enabled in Advanced-user mode also <sup>[1]</sup>, is there a way I can achieve this by editing the userChrome or userContent? 

<sup>[1]: (I see no correlation between being an advanced user and having to remember what pictures someone chose to associate with what actions, and it's a waste of our short-term memory to do so.)</sup>

**Comment by Gitoffthelawn** [comment]
Great question.

I looked into it, and I think I found a way to do it.  Setting native tooltips appears to currently be outside the scope of CSS, but you can use `:hover` to create a box when hovering over an item.  In order to have it appear after a time delay, you should be able to implement a timed animation or transformation.

I was going to implement it, but I didn't feel like the time spent would be worth it.  If you choose to try it, and want to include it in uBlock Deluxe, I would be happy to add your code.

BTW, I have a newer version of uBlock Deluxe if you or anyone else is interested.

**Comment by digital-carver** [comment]
Wow, thanks for looking into this and replying so quickly. 

It seems like you're describing creating new tooltips ourselves, is that the only available option? uBlock0 already has tooltips and they just get disabled when you check the "I'm an advanced user" checkbox. So I was hoping we could just flip some boolean switch that correspond's to this feature in uBlock0 in the user files and be done with it easily. :) 

I looked into the uBlock0 code after writing the above, and it looks like the tooltips get disabled [by a check in the Javascript code](https://github.com/gorhill/uBlock/blob/master/src/js/popup.js#L810) rather than by setting some CSS class. Given this, I guess there's no easy way we can get in the middle of it and enable the existing tooltips? Or is there?

And I'm definitely interested in checking out a newer version, uBlock Deluxe has already made my uB0 usage much more pleasant!

**Comment by Gitoffthelawn** [comment]
My conclusion matches yours: That due to how they are implemented in uBlock Origin, toggling the tooltips requires a javascript injection, and cannot be accomplished via CSS.  The only workaround I have figured out is to create new tooltips ourselves.  I'm open to other ideas or solutions as well.

Since you are interested in a newer version of uBlock Deluxe, I'll upload one in a few minutes.  I have not tested it as much as previous versions, but it does include many new enhancements you may appreciate.

**Comment by Gitoffthelawn** [comment]
Updated to v4.4.0

Enjoy! :-)

**Comment by digital-carver** [comment]
Thanks a lot for taking the time to look into this. I'll update you if I do get the time to implement the tooltips this way. 

And the new css code changes look great, very thoughtful stuff, can't wait to restart my Fx and check them out visually!

**Comment by Gitoffthelawn** [comment]
Thanks!  Enjoy!
